import { v2Query } from "./db.js";

export async function listVehicles(){return (await v2Query("SELECT v.*,d.full_name driver_name,d.phone driver_phone,s.name site_name FROM fleet_erp_v2.vehicles v LEFT JOIN fleet_erp_v2.drivers d ON d.id=v.driver_id LEFT JOIN fleet_erp_v2.sites s ON s.id=v.site_id ORDER BY v.plate_number,v.plate_code")).rows;}
export async function getVehicle(id){return (await v2Query("SELECT v.*,d.full_name driver_name,d.phone driver_phone,s.name site_name FROM fleet_erp_v2.vehicles v LEFT JOIN fleet_erp_v2.drivers d ON d.id=v.driver_id LEFT JOIN fleet_erp_v2.sites s ON s.id=v.site_id WHERE v.id=$1",[id])).rows[0]||null;}
export async function updateVehicle(id,x){return (await v2Query("UPDATE fleet_erp_v2.vehicles SET plate_number=COALESCE($2,plate_number),plate_code=COALESCE($3,plate_code),make=COALESCE($4,make),model=COALESCE($5,model),year=COALESCE($6,year),site_id=COALESCE($7,site_id),driver_id=COALESCE($8,driver_id),legacy_location=COALESCE($9,legacy_location),legacy_driver_name=COALESCE($10,legacy_driver_name),legacy_driver_phone=COALESCE($11,legacy_driver_phone),current_km=COALESCE($12,current_km),last_oil_km=COALESCE($13,last_oil_km),oil_interval_km=COALESCE($14,oil_interval_km),last_oil_change_date=COALESCE($15,last_oil_change_date),inspection_last_date=COALESCE($16,inspection_last_date),inspection_due_date=COALESCE($17,inspection_due_date),registration_expiry=COALESCE($18,registration_expiry),insurance_expiry=COALESCE($19,insurance_expiry),status=COALESCE($20,status),notes=COALESCE($21,notes),updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *",[id,x.plateNumber??null,x.plateCode??null,x.make??null,x.model??null,x.year??null,x.siteId??null,x.driverId??null,x.legacyLocation??null,x.legacyDriverName??null,x.legacyDriverPhone??null,x.currentKm??null,x.lastOilKm??null,x.oilIntervalKm??null,x.lastOilChangeDate??null,x.inspectionLastDate??null,x.inspectionDueDate??null,x.registrationExpiry??null,x.insuranceExpiry??null,x.status??null,x.notes??null])).rows[0]||null;}
export async function recordOilChange(id,x){return (await v2Query("UPDATE fleet_erp_v2.vehicles SET last_oil_km=$2,last_oil_change_date=$3,oil_interval_km=COALESCE($4,oil_interval_km),updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *",[id,x.km,x.date||new Date().toISOString().slice(0,10),x.intervalKm??null])).rows[0]||null;}
export async function listDrivers(){return (await v2Query("SELECT d.*,s.name site_name FROM fleet_erp_v2.drivers d LEFT JOIN fleet_erp_v2.sites s ON s.id=d.site_id ORDER BY d.full_name")).rows;}
export async function createDriver(x){return (await v2Query("INSERT INTO fleet_erp_v2.drivers(employee_no,full_name,phone,status,site_id) VALUES($1,$2,$3,$4,$5) RETURNING *",[x.employeeNo||null,x.fullName,x.phone||"",x.status||"Active",x.siteId||null])).rows[0];}
export async function listSites(){return (await v2Query("SELECT * FROM fleet_erp_v2.sites ORDER BY name")).rows;}
export async function createSite(x){return (await v2Query("INSERT INTO fleet_erp_v2.sites(code,name,region,campus_manager,phone,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[x.code||null,x.name,x.region||"",x.campusManager||"",x.phone||"",x.status||"Active"])).rows[0];}

export async function listProjects(){return (await v2Query("SELECT p.*,s.name site_name FROM fleet_erp_v2.projects p LEFT JOIN fleet_erp_v2.sites s ON s.id=p.site_id ORDER BY p.start_date DESC NULLS LAST,p.id DESC")).rows;}
export async function listMaintenance(){return (await v2Query("SELECT w.*,v.plate_number,v.plate_code,s.name site_name FROM fleet_erp_v2.maintenance_work_orders w LEFT JOIN fleet_erp_v2.vehicles v ON v.id=w.vehicle_id LEFT JOIN fleet_erp_v2.sites s ON s.id=w.site_id ORDER BY w.reported_date DESC,w.id DESC")).rows;}

export async function listWarehouse(){return (await v2Query("SELECT ws.*,wl.code location_code,wl.name location_name,wi.item_code,wi.name item_name,wi.unit,wi.min_stock FROM fleet_erp_v2.warehouse_stock ws JOIN fleet_erp_v2.warehouse_locations wl ON wl.id=ws.location_id JOIN fleet_erp_v2.warehouse_items wi ON wi.id=ws.item_id ORDER BY wi.name,wl.code")).rows;}
export async function seedWarehouseLocations(){const rows=[["MAIN","Main Warehouse"],["UQL","Uqlat Al-Suqour"],["HAD","Al-Haddar"],["SAB","Al Sabiyah"],["QUW","Al Quwayiyah"],["MAH","Mahd ad Dhahab"],["WB","Wadi Bida"],["HUL","Al-Halifa"]];for(const x of rows)await v2Query("INSERT INTO fleet_erp_v2.warehouse_locations(code,name) VALUES($1,$2) ON CONFLICT(code) DO NOTHING",x);return listWarehouse();}

export async function listPurchaseRequests(){return (await v2Query("SELECT pr.*,s.name site_name,u.full_name requester_name FROM fleet_erp_v2.purchase_requests pr LEFT JOIN fleet_erp_v2.sites s ON s.id=pr.site_id LEFT JOIN fleet_erp_v2.users u ON u.id=pr.requested_by ORDER BY pr.created_at DESC")).rows;}
export async function createPurchaseRequest(x){return (await v2Query("INSERT INTO fleet_erp_v2.purchase_requests(request_no,requested_by,site_id,department,status,notes) VALUES($1,$2,$3,$4,'Pending',$5) RETURNING *",[x.requestNo||"PR-"+Date.now(),x.requestedBy||null,x.siteId||null,x.department||"",x.notes||""])).rows[0];}

export async function listTickets(){return (await v2Query("SELECT t.*,v.plate_number,v.plate_code,s.name site_name,u.full_name reporter_name FROM fleet_erp_v2.tickets t LEFT JOIN fleet_erp_v2.vehicles v ON v.id=t.vehicle_id LEFT JOIN fleet_erp_v2.sites s ON s.id=t.site_id LEFT JOIN fleet_erp_v2.users u ON u.id=t.reported_by ORDER BY t.opened_at DESC")).rows;}
export async function createTicket(x){return (await v2Query("INSERT INTO fleet_erp_v2.tickets(title,category,priority,status,vehicle_id,site_id,reported_by,assigned_to,description) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",[x.title,x.category||"",x.priority||"Medium",x.status||"Open",x.vehicleId||null,x.siteId||null,x.reportedBy||null,x.assignedTo||null,x.description||""])).rows[0];}
