import { v2Query } from "./db.js";

export async function listVehicles(){return (await v2Query("SELECT v.*,d.full_name driver_name,d.phone driver_phone,s.name site_name FROM fleet_erp_v2.vehicles v LEFT JOIN fleet_erp_v2.drivers d ON d.id=v.driver_id LEFT JOIN fleet_erp_v2.sites s ON s.id=v.site_id ORDER BY v.plate_number,v.plate_code")).rows;}
export async function createVehicle(x){return (await v2Query("INSERT INTO fleet_erp_v2.vehicles(plate_number,plate_code,make,model,year,site_id,driver_id,current_km,last_oil_km,oil_interval_km,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *",[String(x.plateNumber||"").trim(),String(x.plateCode||"").trim().toUpperCase(),x.make||"",x.model||"",x.year||null,x.siteId||null,x.driverId||null,x.currentKm||0,x.lastOilKm||0,x.oilIntervalKm||5000,x.status||"Active"])).rows[0];}
export async function listDrivers(){return (await v2Query("SELECT d.*,s.name site_name FROM fleet_erp_v2.drivers d LEFT JOIN fleet_erp_v2.sites s ON s.id=d.site_id ORDER BY d.full_name")).rows;}
export async function createDriver(x){return (await v2Query("INSERT INTO fleet_erp_v2.drivers(employee_no,full_name,phone,status,site_id) VALUES($1,$2,$3,$4,$5) RETURNING *",[x.employeeNo||null,x.fullName,x.phone||"",x.status||"Active",x.siteId||null])).rows[0];}
export async function listSites(){return (await v2Query("SELECT * FROM fleet_erp_v2.sites ORDER BY name")).rows;}
export async function createSite(x){return (await v2Query("INSERT INTO fleet_erp_v2.sites(code,name,region,campus_manager,phone,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[x.code||null,x.name,x.region||"",x.campusManager||"",x.phone||"",x.status||"Active"])).rows[0];}

export async function listProjects(){return (await v2Query("SELECT p.*,s.name site_name FROM fleet_erp_v2.projects p LEFT JOIN fleet_erp_v2.sites s ON s.id=p.site_id ORDER BY p.start_date DESC NULLS LAST,p.id DESC")).rows;}
export async function listMaintenance(){return (await v2Query("SELECT w.*,v.plate_number,v.plate_code,s.name site_name FROM fleet_erp_v2.maintenance_work_orders w LEFT JOIN fleet_erp_v2.vehicles v ON v.id=w.vehicle_id LEFT JOIN fleet_erp_v2.sites s ON s.id=w.site_id ORDER BY w.reported_date DESC,w.id DESC")).rows;}

export async function listWarehouse(){return (await v2Query("SELECT ws.*,wl.code location_code,wl.name location_name,wi.item_code,wi.name item_name,wi.unit,wi.min_stock FROM fleet_erp_v2.warehouse_stock ws JOIN fleet_erp_v2.warehouse_locations wl ON wl.id=ws.location_id JOIN fleet_erp_v2.warehouse_items wi ON wi.id=ws.item_id ORDER BY wi.name,wl.code")).rows;}
export async function seedWarehouseLocations(){const rows=[["MAIN","Main Warehouse"],["UQL","Uqlat Al-Suqour"],["HAD","Al-Haddar"],["SAB","Al Sabiyah"],["QUW","Al Quwayiyah"],["MAH","Mahd ad Dhahab"],["WB","Wadi Bida"],["HUL","Al-Halifa"]];for(const x of rows)await v2Query("INSERT INTO fleet_erp_v2.warehouse_locations(code,name) VALUES($1,$2) ON CONFLICT(code) DO NOTHING",x);return listWarehouse();}

export async function listPurchaseRequests(){return (await v2Query("SELECT pr.*,s.name site_name,u.full_name requester_name FROM fleet_erp_v2.purchase_requests pr LEFT JOIN fleet_erp_v2.sites s ON s.id=pr.site_id LEFT JOIN fleet_erp_v2.users u ON u.id=pr.requested_by ORDER BY pr.created_at DESC")).rows;}
export async function createPurchaseRequest(x){return (await v2Query("INSERT INTO fleet_erp_v2.purchase_requests(request_no,requested_by,site_id,department,status,notes) VALUES($1,$2,$3,$4,'Pending',$5) RETURNING *",[x.requestNo||"PR-"+Date.now(),x.requestedBy||null,x.siteId||null,x.department||"",x.notes||""])).rows[0];}

export async function listTickets(){return (await v2Query("SELECT t.*,v.plate_number,v.plate_code,s.name site_name,u.full_name reporter_name FROM fleet_erp_v2.tickets t LEFT JOIN fleet_erp_v2.vehicles v ON v.id=t.vehicle_id LEFT JOIN fleet_erp_v2.sites s ON s.id=t.site_id LEFT JOIN fleet_erp_v2.users u ON u.id=t.reported_by ORDER BY t.opened_at DESC")).rows;}
export async function createTicket(x){return (await v2Query("INSERT INTO fleet_erp_v2.tickets(title,category,priority,status,vehicle_id,site_id,reported_by,assigned_to,description) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",[x.title,x.category||"",x.priority||"Medium",x.status||"Open",x.vehicleId||null,x.siteId||null,x.reportedBy||null,x.assignedTo||null,x.description||""])).rows[0];}
