import { useEffect, useState } from 'react';
import api from '../api/client';

const initial = { enabled: false, webhookUrl: '', mode: 'manual', notes: '' };

export default function PowerAutomateIntegration({ user }) {
  const [config, setConfig] = useState(initial);
  const [logs, setLogs] = useState([]);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  const load = async () => {
    setBusy(true); setError('');
    try {
      const r = await api.get('/integrations/power-automate');
      setConfig({ ...initial, ...(r.data.config || {}) });
      setLogs(Array.isArray(r.data.logs) ? r.data.logs : []);
    } catch (e) {
      setError(e?.response?.data?.message || e?.message || 'Unable to load integration settings.');
    } finally { setBusy(false); }
  };
  useEffect(() => { load(); }, []);

  const save = async () => {
    setBusy(true); setMessage(''); setError('');
    try {
      const r = await api.put('/integrations/power-automate', config);
      setConfig({ ...initial, ...(r.data.config || config) });
      setMessage('Settings saved to the ERP database. / تم حفظ الإعدادات في قاعدة بيانات النظام.');
      await load();
    } catch (e) {
      setError(e?.response?.data?.message || e?.message || 'Unable to save settings.');
    } finally { setBusy(false); }
  };

  const recordManual = async (eventType) => {
    setBusy(true); setMessage(''); setError('');
    try {
      await api.post('/integrations/power-automate/log', {
        eventType,
        status: 'manual',
        details: 'Recorded from Power Automate Integration page; manual workflow remains available.'
      });
      setMessage('Manual action recorded in the ERP database. / تم تسجيل الإجراء اليدوي.');
      await load();
    } catch (e) {
      setError(e?.response?.data?.message || e?.message || 'Unable to record action.');
    } finally { setBusy(false); }
  };

  const field = { width: '100%', padding: '10px 12px', border: '1px solid var(--border-color, #cbd5e1)', borderRadius: 8, background: 'var(--input-bg, white)', color: 'var(--text-color, #0f172a)', boxSizing: 'border-box' };
  return <div className="hub-page">
    <div className="panel" style={{ marginBottom: 16 }}>
      <h1 style={{ marginTop: 0 }}>Power Automate Integration / تكامل Power Automate</h1>
      <p style={{ color: '#64748b' }}>Owner control center for email automation, contractor/campus links, flow status, and audit history.</p>
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
        <span className="badge">ERP Database: source of truth</span>
        <span className="badge">{config.enabled ? 'Automation enabled' : 'Manual mode'}</span>
      </div>
    </div>

    {message && <div className="alert alert-success" role="status">{message}</div>}
    {error && <div className="alert alert-error" role="alert">{error}</div>}

    <div className="panel" style={{ marginBottom: 16 }}>
      <h2>Connection Settings / إعدادات الربط</h2>
      <p style={{ color: '#64748b' }}>Settings and activity records are stored in the ERP database. Keep the manual workflow available if Microsoft connectivity is unavailable during tenant migration.</p>
      <label style={{ display: 'flex', alignItems: 'center', gap: 10, margin: '12px 0' }}>
        <input type="checkbox" checked={!!config.enabled} onChange={e => setConfig(c => ({ ...c, enabled: e.target.checked }))} />
        <strong>Enable Power Automate integration / تفعيل الربط</strong>
      </label>
      <label style={{ display: 'block', margin: '12px 0 6px' }}>Power Automate HTTP endpoint / رابط التدفق</label>
      <input style={field} type="url" placeholder="https://prod-xx.region.logic.azure.com/..." value={config.webhookUrl || ''} onChange={e => setConfig(c => ({ ...c, webhookUrl: e.target.value }))} />
      <p style={{ color: '#64748b', fontSize: 13 }}>Paste the URL generated by your approved Power Automate flow. Do not paste passwords or API secrets here.</p>
      <label style={{ display: 'block', margin: '12px 0 6px' }}>Workflow mode / طريقة العمل</label>
      <select style={field} value={config.mode || 'manual'} onChange={e => setConfig(c => ({ ...c, mode: e.target.value }))}>
        <option value="manual">Manual fallback / يدوي</option>
        <option value="hybrid">Hybrid — save in ERP, prepare flow payload / مختلط</option>
        <option value="automated">Automated / تلقائي</option>
      </select>
      <label style={{ display: 'block', margin: '12px 0 6px' }}>Notes / ملاحظات</label>
      <textarea style={{ ...field, minHeight: 90 }} value={config.notes || ''} onChange={e => setConfig(c => ({ ...c, notes: e.target.value }))} placeholder="Tenant, connector owner, migration notes..." />
      <div style={{ display: 'flex', gap: 8, marginTop: 16, flexWrap: 'wrap' }}>
        <button className="btn btn-primary" onClick={save} disabled={busy}>{busy ? 'Saving…' : 'Save Settings / حفظ الإعدادات'}</button>
        <button className="btn" onClick={() => recordManual('manual_email_prepared')} disabled={busy}>Record Manual Email / تسجيل تجهيز البريد</button>
        <button className="btn" onClick={() => recordManual('manual_link_prepared')} disabled={busy}>Record Link Prepared / تسجيل تجهيز الرابط</button>
      </div>
    </div>

    <div className="panel" style={{ marginBottom: 16 }}>
      <h2>Workflow / دورة العمل</h2>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(190px,1fr))', gap: 12 }}>
        {[
          ['1', 'Maintenance request', 'طلب الصيانة'],
          ['2', 'Assignment email', 'إيميل التعيين'],
          ['3', 'Contractor completion link', 'رابط إتمام المقاول'],
          ['4', 'Campus YES / NO', 'تأكيد الكامبوس'],
          ['5', 'Owner cost & closure', 'التكلفة والإغلاق النهائي']
        ].map(([n, title, ar]) => <div key={n} style={{ border: '1px solid #e2e8f0', borderRadius: 10, padding: 14 }}>
          <div style={{ fontSize: 12, color: '#64748b' }}>STEP {n}</div><strong>{title}</strong><div style={{ color: '#64748b', fontSize: 13 }}>{ar}</div>
        </div>)}
      </div>
    </div>

    <div className="panel">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
        <h2 style={{ margin: 0 }}>Audit History / سجل الإجراءات</h2>
        <button className="btn" onClick={load} disabled={busy}>Refresh / تحديث</button>
      </div>
      {busy && !logs.length ? <p>Loading…</p> : !logs.length ? <p style={{ color: '#64748b' }}>No integration actions recorded yet. / لا توجد إجراءات مسجلة بعد.</p> :
        <div style={{ overflowX: 'auto', marginTop: 12 }}><table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead><tr>{['Time / الوقت','Action / الإجراء','Status / الحالة','User / المستخدم','Details / التفاصيل'].map(h => <th key={h} style={{ textAlign: 'left', padding: 10, borderBottom: '1px solid #e2e8f0' }}>{h}</th>)}</tr></thead>
          <tbody>{logs.map(row => <tr key={row.id}><td style={{ padding: 10, borderBottom: '1px solid #e2e8f0', whiteSpace: 'nowrap' }}>{row.created_at ? new Date(row.created_at).toLocaleString() : '—'}</td><td style={{ padding: 10, borderBottom: '1px solid #e2e8f0' }}>{row.event_type}</td><td style={{ padding: 10, borderBottom: '1px solid #e2e8f0' }}>{row.status}</td><td style={{ padding: 10, borderBottom: '1px solid #e2e8f0' }}>{row.username || '—'}</td><td style={{ padding: 10, borderBottom: '1px solid #e2e8f0' }}>{row.details || '—'}</td></tr>)}</tbody>
        </table></div>}
    </div>
  </div>;
}
