// Print utility for reports
export function printContent(title, subtitle) {
  const printWindow = window.open('', '_blank');
  const mainContent = document.querySelector('.main').cloneNode(true);
  
  // Remove non-printable elements
  mainContent.querySelectorAll('.btn, .btn-row, .theme-toggle, button, .no-print').forEach(el => el.remove());
  
  const styles = `
    <style>
      * { box-sizing: border-box; }
      body {
        font-family: 'Segoe UI', Tahoma, Arial, sans-serif;
        color: #1e293b;
        background: white;
        padding: 20px;
        margin: 0;
      }
      .print-header {
        border-bottom: 3px solid #1e3a8a;
        padding-bottom: 12px;
        margin-bottom: 20px;
        display: flex;
        justify-content: space-between;
        align-items: flex-end;
      }
      .print-header h1 {
        color: #1e3a8a;
        font-size: 26px;
        margin: 0;
      }
      .print-header .meta {
        font-size: 12px;
        color: #64748b;
        text-align: right;
      }
      .panel {
        border: 1px solid #cbd5e1;
        border-radius: 8px;
        padding: 16px;
        margin-bottom: 16px;
        page-break-inside: avoid;
      }
      .panel h2 {
        font-size: 18px;
        margin: 0 0 12px 0;
        color: #1e3a8a;
      }
      .cards-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
        gap: 12px;
        margin-bottom: 16px;
      }
      .card {
        border: 1px solid #cbd5e1;
        border-radius: 8px;
        padding: 14px;
        background: #f8fafc;
      }
      .card h3 {
        font-size: 12px;
        color: #64748b;
        margin: 0 0 6px 0;
        text-transform: uppercase;
      }
      .card .big-number {
        font-size: 28px;
        font-weight: bold;
        color: #1e3a8a;
        margin: 0;
      }
      .card .sub {
        font-size: 11px;
        color: #94a3b8;
        margin-top: 4px;
      }
      table {
        width: 100%;
        border-collapse: collapse;
        font-size: 12px;
        margin-top: 8px;
      }
      th {
        background: #eff6ff;
        color: #1e3a8a;
        text-align: left;
        padding: 8px 10px;
        border-bottom: 2px solid #1e3a8a;
        font-size: 11px;
        text-transform: uppercase;
      }
      td {
        padding: 8px 10px;
        border-bottom: 1px solid #e2e8f0;
      }
      tr:nth-child(even) td {
        background: #f8fafc;
      }
      .status-badge {
        display: inline-block;
        padding: 2px 8px;
        border-radius: 10px;
        font-size: 10px;
        font-weight: 600;
        border: 1px solid #cbd5e1;
      }
      .footer {
        margin-top: 30px;
        padding-top: 12px;
        border-top: 2px solid #cbd5e1;
        text-align: center;
        font-size: 11px;
        color: #64748b;
      }
      @media print {
        .panel { page-break-inside: avoid; }
        body { padding: 0; }
      }
    </style>
  `;
  
  const now = new Date();
  const dateStr = now.toLocaleString('en-GB', { 
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit'
  });
  
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      ${styles}
    </head>
    <body>
      <div class="print-header">
        <div>
          <h1>Fleet &amp; Camp Maintenance ERP</h1>
          <div style="font-size: 14px; color: #475569; margin-top: 4px;">${title}${subtitle ? " — " + subtitle : ""}</div><div style="font-size: 11px; color: #64748b; margin-top: 3px;">System Generated Report</div>
        </div>
        <div class="meta">
          <div><strong>Generated:</strong> ${dateStr}</div>
          <div><strong>System:</strong> Fleet &amp; Camp Maintenance ERP</div>
        </div>
      </div>
      ${mainContent.innerHTML}
      <div class="footer">
        This report was auto-generated by Fleet &amp; Camp Maintenance ERP • Page 1
      </div>
    </body>
    </html>
  `);
  
  printWindow.document.close();
  
  setTimeout(() => {
    printWindow.focus();
    printWindow.print();
  }, 300);
}
